name: Report Build and Publish

permissions:
  contents: write


# Запускаем по расписанию: каждый день в 00:00 UTC (можно менять)
#  schedule:
#    - cron: '0 0 * * *'
on:
  workflow_dispatch:        # а также можно запускать вручную

jobs:
  build_and_deploy:
    runs-on: self-hosted # ubuntu-latest # 

    steps:
      # 1) Клонируем репо целиком, чтобы появилась папка reports/ и docs/ (от прошлого раза)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # нужно, чтобы сохранялись все ветки и можно было коммитить в publish
          persist-credentials: true

      # 2) Клонируем приветный репозиторий
      - name: Checkout reports repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          repository: dperov-org/ai-bot       # замените your-org/reports-repo на точный owner/name приватного репо
          path: ai-bot                    # куда клонируем (подпапка внутри рабочего каталога)
#          token: ${{ secrets.PAT }}  # PAT с правом доступа к приватному репо


      # 2) Устанавливаем Python и зависимости
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Устанавливаем зависимости приватного репо
      - name: Install reports-repo dependencies
        run: |
          if [ -f ai-bot/requirements.txt ]; then
            pip install -r ai-bot/requirements.txt
          fi

      - name: Create .env file with secrets
        run: |
          cat <<EOF > ai-bot/.env
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          DB_PASSWORD=${{ secrets.TELEGRAM_TOKEN }}
          EOF


      # 3) Запускаем скрипт генерации отчёта
      - name: Generate report (Markdown + images)
        run: |
          python reports/generate_reports.py

      # 4) Делаем git-коммит изменений в папку docs/ (если они есть) и пушим обратно в publish
      - name: Commit and push docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Проверим, есть ли изменения (новые/обновлённые файлы в docs/)
          git add docs/
          if ! git diff --cached --quiet; then
            git commit -m "📈 Auto-update report: $(date -u +'%Y-%m-%d %H:%M UTC')"
            git push origin HEAD:publish
          else
            echo "No changes in docs/, skip commit."
          fi

      # 5) (опционально) Вывести ссылку на Pages в логах
      - name: Show GitHub Pages URL
        run: |
          echo "Pages should be available at https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
